# Generated by Django 5.2 on 2025-04-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_categorie_remove_product_category_remove_order_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='etat',
            field=models.CharField(choices=[('neuf', 'Neuf'), ('occasion', 'Occasion'), ('tres_bon', 'Très bon état'), ('bon', 'Bon état'), ('acceptable', 'Acceptable')], default='occasion', max_length=20, verbose_name='État'),
        ),
    ]
