# Generated by Django 5.2 on 2025-04-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='vente_confirmee',
            field=models.BooleanField(default=False, verbose_name='Vente confirmée par le vendeur'),
        ),
    ]
