# Generated by Django 5.2 on 2025-04-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorie_tag_remove_comment_blog_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name="Image de l'article"),
        ),
    ]
